config/routes.rb
Rails.application.routes.draw do

  resources :executors
  resources :categories
  resources :orders do
    resources :services
  end
  resources :customers
  root 'orders#index'
  resources :reports do
    get :xlsx, to: 'reports#xlsx'
  end
end

app/models/executor.rb
class Executor < ApplicationRecord
  has_many :orders

  validates :name, presence: true
end

app/controllers/executors_controller.rb
class ExecutorsController < ApplicationController
  before_action :set_executor, only: %i[ show edit update destroy ]

  def index
    @executors = Executor.all
  end

  def show
  end

  def new
    @executor = Executor.new
  end

  def edit
  end

  def create
    @executor = Executor.new(executor_params)
    respond_to do |format|
      if @executor.save
        format.html { redirect_to executors_path, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @executor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @executor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @executor.update(executor_params)
        format.html { redirect_to executors_path, notice: "Executor was successfully updated." }
        format.json { render :show, status: :ok, location: @executor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @executor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @executor.destroy
    respond_to do |format|
      format.html { redirect_to  executors_path, notice: "Executor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_executor
    @executor ||= Executor.find(params[:id])
  end

  def executor_params
    params.require(:executor).permit(:name)
  end
end

app/helpers/executors_helper.rb
module ExecutorsHelper
end

app/views/executors/_form.html.erb
<%= form_with(model: @executor, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/executors/create.html.erb
<h1>Executors#create</h1>
<p>Find me in app/views/executors/create.html.erb</p>

app/views/executors/destroy.html.erb
<h1>Executors#destroy</h1>
<p>Find me in app/views/executors/destroy.html.erb</p>

app/views/executors/edit.html.erb
<%= render 'form'%>

app/views/executors/index.html.erb
<h4>  Работники: </h4>
<% @executors.order(id: :asc).each do |e| %>
  <div>
    <%= link_to e.name, e %>
    <%= link_to 'Редактировать', edit_executor_path(e) %> |
    <%= link_to 'Удалить', e, method: :delete %>
  </div>
<% end %>
<%= link_to 'Создать', new_executor_path%>

app/views/executors/show.html.erb
<h1>Executors#show</h1>
<p>Find me in app/views/executors/show.html.erb</p>

app/views/executors/update.html.erb
<h1>Executors#update</h1>
<p>Find me in app/views/executors/update.html.erb</p>