config/routes.rb
Rails.application.routes.draw do

  resources :executors
  resources :categories
  resources :orders do
    resources :services
  end
  resources :customers
  root 'orders#index'
  resources :reports do
    get :xlsx, to: 'reports#xlsx'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders

  validates :name, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show edit update destroy]

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def show
  end

  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_url, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customers_path, notice: "customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to  customers_path, notice: "customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def customer_params
    params.fetch(:customer, {}).permit(:name)
  end

  def set_customer
    @customer ||= Customer.find(params[:id])
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: @customer, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/create.html.erb
<h1>Customer#create</h1>
<p>Find me in app/views/customer/create.html.erb</p>

app/views/customers/destroy.html.erb
<h1>Customer#destroy</h1>
<p>Find me in app/views/customer/destroy.html.erb</p>

app/views/customers/index.html.erb
<h4>  Клиенты: </h4>
<% @customers.order(id: :asc).each do |c| %>
  <div>
    <%= link_to c.name, c %>
    <%= link_to 'Редактировать', edit_customer_path(c) %> |
    <%= link_to 'Удалить', c, method: :delete %>
  </div>
<% end %>
<%= link_to 'Создать', new_customer_path%>

app/views/customers/show.html.erb
<%= @customer.name%>

app/views/customers/update.html.erb
<%= render 'form'%>