config/routes.rb
Rails.application.routes.draw do

  resources :executors
  resources :categories
  resources :orders do
    resources :services
  end
  resources :customers
  root 'orders#index'
  resources :reports do
    get :xlsx, to: 'reports#xlsx'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :executor
  belongs_to :category
  has_many :order_reports, dependent: :destroy
  has_many :reports, through: :order_reports

  has_many :services, dependent: :destroy

  validates :category, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  def index
    @orders = Order.includes(:services, :customer, :category, :executor).all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create

    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_order
      @order ||= Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:customer_id,:category_id, :executor_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= form.label :заказчик%>
    <%= form.collection_select :customer_id,  Customer.all, :id, :name%>
  </div>
  <div class="actions">
    <%= form.label :категория %>
    <%= form.collection_select :category_id , Category.all, :id, :category_type%>
  </div>
  <div class="actions">
    <%= form.label :работник %>
    <%= form.collection_select :executor_id , Executor.all, :id, :name%>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class="table-info">
  <thead>
    <tr>
      <th colspan="3"></th>
      <th class="text-center">ID</th>
      <th class="text-center">Работы</th>
      <th class="text-center">Заказчик</th>
      <th class="text-center">Категория</th>
      <th class="text-center">Работник</th>
      <th class="text-center" colspan="2">Редактирование</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <th colspan="3"></th>
        <td class="text-center"><%= order.id %></td>
        <td class="text-center"><%= link_to order.services.map(&:service_type).join(', ').truncate(15), order %></td>
        <td class="text-center"> <%= order.customer.name %></td>
        <td class="text-center"> <%= order.category.category_type %></td>
        <td class="text-center"> <%= order.executor.name %></td>
        <td class="text-center"><%= link_to 'Edit', edit_order_path(order) %></td>
        <td class="text-center"><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h5>Заказчик: <%= @order.customer.name%></h5>
<p>
  <b>Категория:</b>
    <%= @order.category.category_type %> |
  <b>Работник:</b>
    <%= @order.executor.name %>
</p>
<h4>Работы: </h4>
  <% @order.services.each do |service| %>
    <div>
      <li><%= service.service_type %>
        <%= link_to 'Редактировать', edit_order_service_path(@order, service) %> |
        <%= link_to 'Удалить', [@order, service], method: :delete %>
      </li>

    </div>
</br>

<% end %>
<%= link_to 'Добавть работы', new_order_service_path(@order) %> |
<%= link_to 'Редактировать', edit_order_path(@order) %> |
<%= link_to 'К заказам', orders_path %>